#ifndef ENUMS_H
#define ENUMS_H

enum TYPE_ENUM {TYPE_FRIDGE = 0, TYPE_BLENDER = 1, TYPE_HEATING = 2, TYPE_SAUNA = 3, TYPE_WASH = 4, TYPE_DISH = 5, TYPE_TV = 6, TYPE_PC = 7, TYPE_LIGHT = 8};
enum POWERED   {POWER_OFF, POWER_QUEUED, POWER_GRANTED_ON, POWER_FORCED_ON};

#endif // ENUMS_H


